import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavbarTab from "@/component/Tab/NavbarTab";
import Banner from "@/component/Banner/Banner";
import { headers } from 'next/headers';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <header className="navbar">
          <div className="navbar-logo">
            <Link href="/">HANTEO DEMO</Link>
          </div>
          <div className="navbar-tab">
            <NavbarTab/>
          </div>
        </header>
        <div className="navbar-placeholder" />

        <div className="banner-wrapper">
          <Banner />
        </div>
        {children}
      </body>
    </html>
  );
}
